# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FIGp5JQSAByToy2UUIgFWdBNdU0EaCwy6nxji8+XxW2DgV3L2jwYig==,iv:COlTxEZ86uKUb+QP9jiHDRJTbzJ81/pWLIKL1qxk1Zc=,tag:oxwxaOEZXFYCH2WdnhxOTQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OXRxdjNRNjV5ZHhVbmYy
        cWdDZ2creUh5bm1pemg2ZkhaZVhMT0pZVEdzClRGcURkZEhMTnlnWjhQNG53SENX
        RlB1a0RCRy9sak82em1KMmtrWnNEQkkKLS0tIGozWDc2NUYyWlM2NlBmL0VUSXkx
        WTdHVGt2ZzB6QjU3dXFTRmVTZGVRY2cKnHtR+b8ntpfK6HEE5t4r1jGz5bUkr4xV
        Lmsb6VDxJ8K9dIAByjNTzJzi34Dpv/RUJTJt6bdBJTZ27msvPMzZ+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T12:01:25Z"
  mac: ENC[AES256_GCM,data:kenmzqzkXsheWN/TV2+oPhEf+c6UIvrkJt4G2YHB5JtORUpvzxTIdQY7lo/OfcO6U0D33OKmPhUNsQgQbD/zej4MrPMPgzXY1iYPxGJ/4mcDBz864+/lfBUwwXmDutAq8UkvfwcF6y8AmRnanQ5Qf33m/i4TYNAKVAAg//9YU18=,iv:JswNzLdaZGxW+KetaIOJujlWRuI2HkMhaSuz2lG3aBQ=,tag:HGWgQErtCH8IIwJl78I/KA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
