# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:20DqDLPO/xgToZQTY/tKLQFb4H3fepVRdRVlOkDGXExa7Gv0xabtkg==,iv:Ong3OjK4S3CutEAXKoj2HJvdu5tx33PjVxygKAV9U0I=,tag:QamYYnhrIy9ajvUxPX4/jQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVm5PMHI1eVZJZGM3eGVs
        RjN5Snd4S0dvT2E0NVViUHNEbUJNcTJqTGpjClZTdG1aWS9uUCtlcW11WENJRHhR
        UWZoUHZiMEp1eUtyK1NJU3ZySTVMaTQKLS0tIGp2TitoM0F4NnljWktQVDBIVWRu
        WjZVdVRPQ1N4UmY4eC81YjU0Und0ancKibfy+fKFriKb/nfmt2+dKe5jsOnEz13f
        d4S78bk25Gj23VeGhVyCkWq3H0lLdxPVQbFG/J6N6bMFhhTtrjceTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-22T00:02:17Z"
  mac: ENC[AES256_GCM,data:kb4UhKye7GNriILBeT04VKoIXyRdeVxiHwkQsfcimUVtweOzAxOoT0jKjp0czeQs7j2wtj3ywyRrRG7FfP5Om+srTvQrNoNkemZpvkuDntSg8CVixIg+33AQaN+FYdtbaCSUxNC79yD2XNOby1jtNo02uLKnX97QjawShQcxjHc=,iv:1p4LWSxXoiTAmsR+3IAXC6NXkrIjfM+5VY+wqbPWr+A=,tag:AteFiJmPojp5q4FzEUMW5Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
