# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:krGEaAIZr1+fSmFPrk6Dqcprh4YkVrw7qSV6DLF0VAfMTObzRDmMbQ==,iv:sVcoODOTZT/s1Tt6bwY6kSjGGZCeLUraSt1za4IqASQ=,tag:hDYTAjTR/icROJ9M77zgCg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaDhpczIxY1FEdWZnVWll
        VnZQRDAyd0VTb1luTEJpaUFaVkdkUHk5ZzNvCnNrRWJHZmxaczdyaWdGZGQwbGJE
        WjBJMVZrVEdwMUk5cFRUa3FtZy96dWsKLS0tIE81aVZjSTUrVHBhc2cwenoySTl3
        dXFjb0pya0xsR2dBaGsrNkRpczQ2VG8K4oxsSgNxsaPn4iueC2SIanoLGrN5vr2h
        4aEzXchTyGWTA3Y643uZ+45mwPC/ALGsLHgOecF3nBlpa9o9tiqdNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-22T11:08:19Z"
  mac: ENC[AES256_GCM,data:KLwNVjDxEmliqnyqJjuiWWJDH0r/X8KNcnhpTVXEiscQIAOdauUiaVgCPIG+vr0i5iCD1DVulgzeY3DE1VwGROZIRpQaNHBZUrNe264Ad/Wh5JwVmEPlkPu1K+OApl+yhLgutwTBCn5zrgz7FsgVEJRVVMOlMIaCq4SrUel+T4g=,iv:Ob25ry4JIU3ntlLJTE9EJJ9G6FGl4lLjprVn4vmbkxQ=,tag:Rvwo883NVka8ZyGY4eulKw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
