# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Ssvl20c2uJjTjRs8s2yG+Bn536Egmetl0I2NfKjzmZI=,iv:8iPVztl+davI05ab7EA+Q5CYZD400nbvnIo2Wq4COHw=,tag:rOf7JBJwnepieoLw++T5gw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM3NZa2kvMnlKM09zTENp
        RExlSlcvSytySjY1UVNITnJ5L3NISUtLY0h3CnE3R3cvYWhSay8xTlBoRHQ5elhO
        Sy9HRmsxb0ZjZWJrRFBZYWZoOXQ5SWMKLS0tIGZ6WGZ4dldxMlRwYkhEL2s3U09R
        M1JkVlFuUEp0U3lvUGNBbDRqZEpJM3cKJO2LkDoCQmH0dgcwjf643YScmtanLB1/
        JyuY2X6VX/IyCUAmrR9nvYFB8WJzv8ZhB5R86UNX0DIwlq7eqVxrrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T00:23:21Z"
  mac: ENC[AES256_GCM,data:w4cQUosWh703e5rJktDRlZ3hHctMg9BGkmBijeM6BY0Z/xM2yv3a+fumNJNCfUVL+IwwzAmO8+NgjsR9+bbtBuvhqTFk11WH0xaFrzXbB/wqKr2V6l3A4fEeW7+DuPtoTIE8Gmi59AkbczJkC8Xj1LFqxOfaGRGRaZMWGnHyW+k=,iv:e8WZOFsa/ihPc751WXZBtkFuJwcSKpu1gk/aXSmyEeA=,tag:f574vNnuyPgDhoj3G7MWDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
