# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:U53JXAXqHFPorxyS37QSelS61fqg+LIavqfdFoGQn3U=,iv:wOgKpMzsTEPUdE0c9gtX8tN0YROBE3nNN3lQ3w9E8fo=,tag:DpVMuLBoruvn77M88ef7RA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQkZiLzdBUzI5MHBJZldY
        cFhtcmR3SlkwV0szaWVTTXk0aWNGOURTaFZRCko0MUltMHZYZ3pzWmNnTFB3Uy8v
        MWt2VHNWbUZJNW54NkdvejZHTnVtcXMKLS0tIDFiU0dOYTVoczVZM281VGRkUEVM
        dDljSEtLMFhWcWdZanVTaGVkZyszNk0KDvChxZKRwPrMhd8o9gHoqNkTrnF0ETHw
        uuiz+Q2BbdBqggOC9QV8TrovqTmLiJJVAsnZc8u2PNzksV1TYbTd2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-25T15:22:50Z"
  mac: ENC[AES256_GCM,data:sbzj7A/2C+bJpBw7tQCy72kRAU9Fa4ts08ZunpY+aA09ZCAkWgAb6HWb+5ZMYIBhFfKrtogUAfRNT/dTlUWamh373CapD6aGEiCsLkfniEEVvLOTtJ+r6Oyh+KyY6rXvHj1UrlqLyQC+gbYAbcle8ntEc42uZjQ+ri5K+PHvJ0E=,iv:z5zbJTgHj2CBEuEaxeD8g1jbQ+sDxbj1MA1KQ6CA/Wk=,tag:aa1wbJu809hcqNgnedu0mA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
