apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:sB2xO2BPCbA=,iv:Kefk4VRQCXCwA+LUklH5GyWpMuGRKT4S10Z/WaGE/dQ=,tag:cqQjXn3IlRobpIgdYxovtA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR2t1cTBhcmk1UFpha3pm
        cFk3OENvNWxmY2Q1bkkzOVBsNHBobTh3Z0hZCkJtT0RCOHVFOHhHclN2L2VjMFFl
        NHJXWHdCYUlPYnJtbHJ0UzRsV0d0VFkKLS0tIFFMQnNqcmM2cGsrVkp5aS9uT0ty
        L29PYjBGS3pVRUF4R3p6cnlzWStma0UKOrkfUb7kdcnCRb8YwQmCrI7aD4HSrOK9
        jdSH/uX1Vxqq2+Zq2V5O0Ny56b/WyWkZ+UQo5pkm3n34Iipt51RTtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T23:54:44Z"
  mac: ENC[AES256_GCM,data:UvMqpUVslkIwbgwJnQPdaI0OxzPBwpWXsqBZyfc2ROegyaShGVq2668LnmHQx7YL0bxOYT3GMz7M/MkySmqanGOs8RoOHxadm1elyHSQYlcBDBqJgQYwu8fU6ykj+XcZN8tHJU0pOA6gVn3yqtOOKvrfvShIpK0APBMqjJ4KaY0=,iv:wxVLGMx+afoZQs45r0Hd80gVXUclY7jeeH1T+9X4Ess=,tag:d4KKqGPPChD5sXI4jjEHYw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
