apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:N6ssTVBB8B4=,iv:oHWHcxOyYKkURCCSvphQE0LsnADH1fQr1VspJg3P4rU=,tag:k87asN7J6hRk18/FT+Ljdg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZGwzYTdEdVpDQ2dZY2FB
        Rkw2OWIzempPMkZidHQxaVFXUGNCOU0rYkJVCnZ3cnA0VU9lc3Q4VnFqb29KTFM2
        bzl6bmsvbS9WREE3RjYwTlMxOENuRGcKLS0tIHMxOUdxL0ZtZ0ZtSEpRVXRQWVVt
        WDZXWUlPY1RDZ1lUMmVjWHJ2Ymw3NncKSuxJZdrE+u5EvrVpA53EnuJ861Usa3Fj
        LRbMdgTJjxspc5DfsOnMIeYnhXkyHDWg0DdbWR+EjflUralsZAU9NA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-22T11:08:19Z"
  mac: ENC[AES256_GCM,data:Deb5f3/OHaxFKKjFsis4x0cL7thMsPW+A55vFfzsLy9w07CAQawR2DUkNZCuCgRid++PE235laZvdsGVoAFGcORBrPIau48HrW9njNe7egDzsKsHpIxDv6ofxuw5aWul2Gsqh2KKyxbwXCLcaI6I0aLaNAVi/UyKk96qzs3FGtI=,iv:tlstdL/Ps+RFo3L4+XtcypBLwc62CwWzIWSUHx5lDZ4=,tag:yENujXU0Ddvzwx/Ch8P4wg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
