apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:MpmRV0Hh6UCD6uhBhBC/2SU+uQs1Vex/ABAbCT9nv+lhGgiaUGJzWs6/gf87CzHxx0jbBOUQai+6JdHwzL9kQcKpTUfynXNV3nM=,iv:WUNpiHP5xhkr1GuP2YTXkXmavMlI/A0LUodi1Meysdk=,tag:4/bQu42wFzzoefb58VdWlw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ztw7aa6rxu0p487vcv7uur3uwznjqm4tcm5tcu0t2duevyeacp4sra36tp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQmVLMDNZU1NuK2o5aG5F
        NHB4MzdqSSs0UXk4OWcra1lIUk1Bemc1d0RjCk5QbnYzNTNaUVVSSDBMY01RWTNp
        K2g0dk1wc1l6MVJJUUxacUVwOGp3MWMKLS0tIC9LSTcvQUlHSEI0UFdtQXIrMmVm
        YWM2VHFIb05ZNjQrYVJRZ1h4MlZXcVEKDT1sRKVEpdKUl8iEmrxfC/iEPncKklqN
        r7wrAc5P4SAfirh6Ac1S1a1Z7YgFUVrSXHQSLtb4VOAE5QfOh/jJag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-22T19:33:11Z"
  mac: ENC[AES256_GCM,data:iSY0ZAONNdvE61pU/xleekthbXFzghOqPIg5SQ/2vGJgqmDBBXq+zEf0uNg8WcbZIP8f5EPbLNUMS1xrvpOcgOltSDZHFkxtEeOmiOKZEVAWUPj5xj3bjp96HWxsL/oWBMVjd6bp6SZI5R59sNQR1IugCExMnJcdL0lLIRDdqPE=,iv:osJPgCVNy4wxnKjxWnVvwBJFyAdeUZMOhFV7CndTZEs=,tag:PlkNjQGoF+WOcSm8xw2sAQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
